### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by arjenpdevries** [xw0078/WebArchiveWithParquetAvro#2]
In the paper, you write

    We use a modified ArchiveUnleashedToolkit for reformating
    WARC to Parquet and Avro. Settings for Parquet/Avro file writing
    are included in the example code repository.

However, I miss the definition of `data` that the file starts with. Could you elaborate how you went from the HDFS directory with CC files to variable `data`?

**Comment by xw0078** [comment]
Hi,

Thanks for the feedback. The 'data' in the example represents the converted data, which does not have an example code. 
I will put the example code and associated 'customized AUT' jar to the repository later.

**Comment by arjenpdevries** [comment]
Thank you, without that essential first step the repository is not really sufficient for replicating your work; adding that would be highly appreciated!

**Comment by xw0078** [comment]
Hi, 
I have updated the repository with new code for data generation and the compiled customized-AUT java package.

Thanks for your feedback.
